In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
a.ndim

1

In [7]:
b.shape

(2, 3)

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.size

3

In [11]:
b.size

6

In [12]:
b.nbytes

48

In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
a[0,5]

6

In [32]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
a[:, 2]

array([ 3, 10])

In [34]:
a[0, 1:-1:2]

array([2, 4, 6])

In [35]:
a[1, 5] =20

a[:,2] =[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [39]:
b = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
b[0,1,:]

array([3, 4])

In [44]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [46]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [48]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [51]:
np.random.rand(4,2)

array([[0.55351542, 0.52236092],
       [0.51544749, 0.01806116],
       [0.82155217, 0.84133905],
       [0.95414576, 0.86172996]])

In [52]:
np.random.randint(7, size=(3,3))

array([[5, 4, 6],
       [6, 3, 4],
       [4, 2, 2]])

In [53]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
c = np.array([[1,2,3]])
r1 = np.repeat(c,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [59]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
halle = np.zeros((7,7))


f = np.ones((5,5))
f[2,2] = 5

halle[1:-1, 1:-1] = f
print(halle)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [65]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [66]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [68]:
a + 2

array([5, 6, 7, 8])

In [69]:
a * 2

array([ 6,  8, 10, 12])

In [72]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(" ")
print(after)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [73]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])